### ISSUE TITLE
Handle CSS class based colors

### ISSUE THREAD

**Issue by martyglaubitz** [inloop/svg2android#17]
Sometimes Tools like Adobe Illustrator, when exporting to SVG, they use a CSS block at the beginning of the generated SVG file to define the colors ass CSS classes like:

``` css
<style type="text/css">
    .st0{fill:#FFDC15;}
    .st2{fill:#FFD21A;}
    .st3{fill:#FFD11A;}
</style>
```

and later on just uses these to style the paths

``` svg
<path class="st2" d="M96.6,116.9l18.6-14.8h21.1l4.2,35c-7.3,8.3-10.1,9.7-20.5,15.1l-2.7-24.9l-20.8,16.7L76.4,129l-2.7,23.3
            c-10-4.9-13.6-7-21.1-15.3l4.3-35h21.2L96.6,116.9L96.6,116.9L96.6,116.9z"/>
<path class="st2" d="M96.6,143.9L76.4,129l-2.7,23.3c-10-4.9-13.6-7-21.1-15.3l4.3-35h21.2l18.5,14.8l0,0l0,0l18.6-14.8h21.1
            l4.2,35c-7.3,8.3-10.1,9.7-20.5,15.1l-2.7-24.9L96.6,143.9z"/>
```

right now, the tool just adds a black fill color and ignores the css class colors
